name: "Mern-app"
services:
  # mongodb:
  #   image: mongo:8.0.3
  #   container_name: mongodb
  #   volumes:
  #     - mongodb-data:/data/db
  #   env_file:
  #     - ./env/mongo.env
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - db-network
  api:
    container_name: node-app
    # depends_on:
    #   - mongodb
    build:  
      context: ./API-jokes
      dockerfile: Dockerfile.prod
    image: node-api-image
    ports:
      - "5000:5000"
    env_file:
      - ./env/server.prod.env
    networks:
      # - db-network
      - server-network
  client:
    container_name: client-app
    depends_on:
      - api
    build:  
      context: ./react-client
      dockerfile: Dockerfile.prod
    image: react-client-image
    ports:
      - "80:80"
    networks:
      - server-network

volumes:
  mongodb-data:
networks:
  # db-network:
  server-network: