name: Build image and deploy to ECS
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_IMAGE_NAME: ecs-demo-node
  REACT_IMAGE_NAME: ecs-demo-client
  AWS_REGION: us-east-1
  ECS_CLUSTER_NAME: ecs-cluster-demo
  ECS_SERVICE_NAME: ecs-demo-SV
  TASK_DEFINITION: ecs-demo-task
  NODE_CONTAINER_NAME: node-app
  REACT_CONTAINER_NAME: client-app

jobs:
  build-image-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ env.NODE_IMAGE_NAME }}
          tags: |
            latest  
            v1.0.${{ github.run_number }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./API-jokes
          file: ./API-jokes/Dockerfile.prod
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
  build-image-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ env.REACT_IMAGE_NAME }}
          tags: |
            latest  
            v1.0.${{ github.run_number }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./react-client
          file: ./react-client/Dockerfile.prod
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
  deploy-to-ecs:
    needs:
        - build-image-node
        - build-image-react
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Render Node container in task definition
        id: render-node-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.NODE_CONTAINER_NAME }}
          image: ${{ vars.DOCKER_USERNAME }}/${{ env.NODE_IMAGE_NAME }}:latest

      - name: Render React container in task definition
        id: render-react-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-node-container.outputs.task-definition }}
          container-name: ${{ env.REACT_CONTAINER_NAME }}
          image: ${{ vars.DOCKER_USERNAME }}/${{ env.REACT_IMAGE_NAME }}:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-react-container.outputs.task-definition }}
          service: ${{env.ECS_SERVICE_NAME}}
          cluster: ${{env.ECS_CLUSTER_NAME}}
          wait-for-service-stability: true
